---

- name: include default vars file
  include_vars: vars/default.yaml

- name: install common apps
  become: true
  apt:
    update_cache: true
    pkg:
      - qemu-guest-agent
      - htop
      - vim
      - net-tools
- name: "Ensure group {{ admin_group }} exists"
  group:
    name: "{{ admin_group }}"
    state: present
- name: "Create User {{ admin_username }} and add to groups"
  user:
    name: "{{ admin_username }}"
    shell: /bin/bash
    comment: "{{ admin_fullname }}"
    group: "{{ admin_group }}"
    groups: adm, sudo
    append: true
    state: present
- name: Create .ssh directory
  file:
    path: "/home/{{ admin_username }}/.ssh"
    owner: "{{ admin_username }}"
    group: "{{ admin_group }}"
    mode: 0700
    state: directory
- name: set authorised key taken from file
  ansible.posix.authorized_key:
    user: "{{ admin_username }}"
    state: present
    key: "{{ lookup('file', admin_ssh_pubkey) }}"

- name: "setup sudo for {{ admin_username }}"
  become: true
  copy:
    dest: "/etc/sudoers.d/{{ admin_username }}"
    content: |
      {{ admin_username }} {{ admin_sudo_opt }}
    mode: 0440
    owner: root
    group: root
  when: allow_nopasswd_sudo

- name: setup NTP server via systemd timesyncd
  import_tasks: timesyncd.yaml

- name: Upgrade packages via APT
  import_tasks: apt_update.yaml
