---

- name: debug gateway
  debug:
    msg: The default gateway is "{{ ansible_default_ipv4.gateway }}"

- name: adding NTP server which is the defalt gateway
  lineinfile: dest='/etc/systemd/timesyncd.conf' line="NTP={{ ansible_default_ipv4.gateway }}" insertafter='EOF' regex="#NTP=" state=present

- name: enable systemd-timesyncd
  ansible.builtin.service:
    name: systemd-timesyncd
    enabled: true
    state: started
- name: "set timezone to {{ admin_timezone }}"
  community.general.timezone:
    name: "{{ admin_timezone }}"
