---

- name: Adding $TELEGRAM_TOKEN ENV VAR to ~/.bashrc
  lineinfile: dest="/home/{{ hass_user }}/.bashrc" line="export TELEGRAM_TOKEN={{ telegram_token }}" insertafter='EOF' regex="export TELEGRAM_TOKEN={{ telegram_token }}" state=present

- name: Adding $TELEGRAM_GROUP ENV VAR to ~/.bashrc
  lineinfile: dest="/home/{{ hass_user }}/.bashrc" line="export TELEGRAM_GROUP={{ telegram_group }}" insertafter='EOF' regex="export TELEGRAM_group={{ telegram_group }}" state=present

- name: Adding $HASS_USER ENV VAR to ~/.bashrc
  lineinfile: dest="/home/{{ hass_user }}/.bashrc" line="export HASS_USER={{ hass_user }}" insertafter='EOF' regex="export HASS_USER={{ hass_user }}" state=present

- name: Adding $HASS_PRIVKEY_PATH ENV VAR to ~/.bashrc
  lineinfile: dest="/home/{{ hass_user }}/.bashrc" line="export HASS_PRIVKEY_PATH={{ hass_privkey_path }}" insertafter='EOF' regex="export HASS_PRIVKEY_PATH={{ hass_privkey_path }}" state=present

- name: Adding $HASS_CONFIG_PATH ENV VAR to ~/.bashrc
  lineinfile: dest="/home/{{ hass_user }}/.bashrc" line="export HASS_CONFIG_PATH={{ hass_path }}" insertafter='EOF' regex="export HASS_CONFIG_PATH={{ hass_path }}" state=present

- name: Adding $NAS_HOST ENV VAR to ~/.bashrc
  lineinfile: dest="/home/{{ hass_user }}/.bashrc" line="export NAS_HOST={{ nas_host }}" insertafter='EOF' regex="export NAS_HOST={{ nas_host }}" state=present

- name: Adding $NAS_BACKUP_PATH ENV VAR to ~/.bashrc
  lineinfile: dest="/home/{{ hass_user }}/.bashrc" line="export NAS_BACKUP_PATH={{ nas_path }}" insertafter='EOF' regex="export NAS_BACKUP_PATH={{ nas_path }}" state=present

- name: cp hass-backup.sh script to /usr/local/bin
  ansible.builtin.copy:
    src: hass-backup.sh
    dest: /usr/local/bin/hass-backup.sh
    owner: "{{ hass_user }}"
    group: "{{ hass_group }}"
    mode: '0755'

- name: "schedule backup via cron every 6 hours to freenas * */6 * * * "
  ansible.builtin.cron:
    user: "{{ hass_user }}"
    name: "hass backup to freenas every 6 hours"
    minute: "21"
    hour: "7"
    job: ". /home/hass/.bashrc;/usr/local/bin/hass-backup.sh 2>&1 > /tmp/hass-backup.log"
