---

- name: include default vars file
  include_vars: vars/default.yaml

- name: "ensure homeassistant group {{ hass_group }} exists"
  group:
    name: "{{ hass_group }}"
    state: present
- name: "create homeassistant user {{ hass_user }}"
  user:
    name: "{{ hass_user }}"
    shell: /bin/bash
    comment: homeassistant
    group: "{{ hass_group }}"
    groups: dialout, sudo
    append: yes
    state: present
- name: "grant sudo access to user {{ hass_user }} for command systemcl restart hass"
  copy:
    dest: "/etc/sudoers.d/{{ hass_user }}"
    mode: 0440
    owner: root
    group: root
    content: |
      hass ALL=(root) NOPASSWD: /bin/systemctl restart hass
      hass ALL=(root) NOPASSWD: /bin/systemctl stop hass
      hass ALL=(root) NOPASSWD: /bin/systemctl start hass

- name: "cp hass-upgrade.sh script to /usr/local/bin"
  ansible.builtin.copy:
    src: hass-upgrade.sh
    dest: /usr/local/bin/hass-upgrade.sh
    owner: "{{ hass_user }}"
    group: "{{ hass_group }}"
    mode: '0755'

- name: setup backup of homeassistant
  import_tasks: backup.yaml
