---

- hosts: all
  become: yes
  tasks: 
  - name: "update apt cache and update packages"
    apt:
      update_cache: true
      upgrade: true

  - name: auto-remove packages
    apt:
      autoremove: true

  - name: install update-manager-core
    apt:
      pkg:
        - update-manager-core
  
  # - name: Run do-release-upgrade non-interactively.
  #   command: do-release-upgrade -f DistUpgradeViewNonInteractive
