---

- name: "Copy lullabies cifs mount file to /etc/systemd/system/{{lullabies.name}}"
  ansible.builtin.template:
    src: sto.mount
    dest: "/etc/systemd/system/{{lullabies.name}}"
    group: root
    mode: 0644
  vars:
    what: "{{ lullabies.remote }}"
    where: "{{ lullabies.local }}"
    options: "{{ lullabies.options }}"
  notify:
   - systemctl-daemon-reload
   - Enable mnt-lullabies.mount


- name: "Copy music cifs mount file to /etc/systemd/system/{{music.name}}"
  ansible.builtin.template:
    src: sto.mount
    dest: "/etc/systemd/system/{{music.name}}"
    group: root
    mode: 0644
  vars:
    what: "{{ music.remote }}"
    where: "{{ music.local }}"
    options: "{{ music.options }}"
  notify:
   - systemctl-daemon-reload
   - Enable mnt-music.mount

- name: "Copy media1 cifs mount file to /etc/systemd/system/{{media1.name}}"
  ansible.builtin.template:
    src: sto.mount
    dest: "/etc/systemd/system/{{media1.name}}"
    group: root
    mode: 0644
  vars:
    what: "{{ media1.remote }}"
    where: "{{ media1.local }}"
    options: "{{ media1.options }}"
  notify:
   - systemctl-daemon-reload
   - Enable opt-media1.mount

- name: "Copy media2 cifs mount file to /etc/systemd/system/{{media2.name}}"
  ansible.builtin.template:
    src: sto.mount
    dest: "/etc/systemd/system/{{media2.name}}"
    group: root
    mode: 0644
  vars:
    what: "{{ media2.remote }}"
    where: "{{ media2.local }}"
    options: "{{ media2.options }}"
  notify:
   - systemctl-daemon-reload
   - Enable opt-media2.mount
