---

- name: include default vars file
  include_vars: vars/default.yaml

- name: Install Plex Dependencies
  become: yes
  apt:
    update_cache: yes
    pkg:
      - cifs-utils
      - build-essential 
      - libglvnd-dev 
      - pkg-config

- name: "Ensure {{ plex_group }} user exists"
  group:
    name: "{{plex_group}}"
    state: present
- name: Create {{plex_user}} User  and add to {{plex_group}} group
  user:
    name: "{{ plex_user }}"
    shell: /bin/bash
    comment: "{{ plex_user }}" 
    group: "{{ plex_group }}"
    groups: "{{ plex_user }}"
    append: yes
    state: present
- name: "Setup Storage interface {{sto_iface_name}}"
  import_tasks: storage_interface.yaml

- name: "Setup cifs shares"
  import_tasks: cifs_shares.yaml
