---

- name: "Check if interface.d has been added to the interfaces file"
  lineinfile:
    state: absent
    path: "/etc/network/interfaces"
    regexp: "^source /etc/network/interfaces.d/*"
  check_mode: true
  changed_when: false
  register: check

- name: Add source /etc/network/interfaces.d/* to interfaces file if not set
  lineinfile:
    state: present
    path: "/etc/network/interfaces"
    line: "source /etc/network/interfaces.d/*"
  when: check.found == 0

- name: "Copy {{sto_iface_name}} settings"
  ansible.builtin.template:
    src: iface.conf
    dest: "/etc/network/interfaces.d/{{sto_iface_name}}"
    group: root
    mode: 0644
